stages:
- test

test:
  stage: test
  image: python:3.6
  before_script:
    - pip install -e .[dev]
  script:
    - tox
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
  tags:
    - gitlab-org

docs:
  stage: test
  image: python:3.6
  before_script:
    - pip install -e .[dev]
  script:
    - sphinx-build -b html docs docs/_build/html
  artifacts:
    paths:
      - docs/_build/html
  tags:
    - gitlab-org