stages:
- test
- docs

image: python:3.6
before_script:
  - pip install -e .[dev]
script:
  - tox

test:
  stage: test
  environment:
    TOXENV: py,codecov
    CODECOV_TOKEN: a6941021-a3bd-4c20-8686-3c6926c28307
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
  artifacts:
    paths:
      - htmlcov
  tags:
    - gitlab-org

test-lint:
  stage: test
  environment:
    TOXENV: lint
  tags:
    - gitlab-org

test-docs:
  stage: test
  environment:
    TOXENV: docs
  tags:
    - gitlab-org

docs:
  stage: docs
  script:
    - sphinx-build -b html docs docs/_build/html
  artifacts:
    paths:
      - docs/_build/html
  tags:
    - gitlab-org