sudo: false
language: python
cache:
  pip: true

stages:
  - test
  - docs

jobs:
  include:
  - stage: test
    matrix:
      include:
        - python: 3.6
          env:  TOXENV=py,codecov
        - python: 3.6
          env: TOXENV=lint
        - python: 3.6
          env: TOXENV=docs
    install: pip install tox
    script: tox

  - stage: docs
    python: 3.6
    install:
      - pip install -e .
      - pip install sphinx
    script: sphinx-build -b html docs docs/_build/html


